### ISSUE TITLE
Persistent File error

### ISSUE THREAD

**Issue by calvinjuarez** [bfricka/less-preview#21]
## Here's what happened.
1. I copied and pasted a block\* of LESS that included two `@import` statements.
2. I commented them out (first `// line`, then `/* block */`),  
   then deleted them,  
   then deleted the entire block and re-pasted it without any `@import`s
3. I took a screenshot and opened this issue

_* If you'd like the full block of text I pasted, I can give it to you._
## Here's that screenshot.

![screen shot 2013-12-19 at 1 06 37 pm](https://f.cloud.github.com/assets/2146819/1785729/44c54a2e-68e9-11e3-8515-81fd134b2b7d.png)
## By the way,

This is fixed by a `localStorage.clear()` call, but I figured I'd let you know about it anyway.

**Comment by bfricka** [comment]
Yes it would be good if you could paste the text in a code block so I can debug. Thanks

**Comment by calvinjuarez** [comment]
No prob.

``` less
/*! Compiled with LESS */
//! ----------

@import '_variables';
@import (reference) '_mixins';

@red:  #e55;
@grey: #999;

.at-viewport(@width) when (isnumber(@width)) {
  @at: ~'@';
  @{at}-ms-viewport { width: @width; }
  @{at}-o-viewport { width: @width; }
  @{at}viewport { width: @width; }
}

.background-stripes (@color) when (iscolor(@color)) {
  @linear-gradient:
    fade(@color,5) 0%, fade(@color,5) 50%,
    @color 50%, @color 100%;
  background: -webkit-linear-gradient(@linear-gradient);
  background: -moz-linear-gradient(@linear-gradient);
  background: -ms-linear-gradient(@linear-gradient);
  background: -o-linear-gradient(@linear-gradient);
  background: linear-gradient(@linear-gradient);
  background-size: 27px 27px;
}

.transform-x(@degrees) {
  transform+: rotateX(@degrees);
}

#format-string-function { /* from http://lesscss.org */
  format-s: %("repetitions: %s file: %s", 1 + 2, "directory/file.less");
}

body {
  @media screen and (-webkit-min-device-pixel-ratio: 0) {
    background: linear-gradient(45deg, #acce55, #0ff);
    &:first-of-type pre::after {
      content: 'highlight: ' attr(class);
    }
  }
  .background-stripes(spin(darken(dodgerblue,10),5));
}

.transform-me {
  transform+: rotateY(20deg);
  .transform-x(30deg);
}

pre.highlighted,
#content, a[data-toggle="modal"] {
  background: url('hatch.png') /* why? */;
  color: lighten(@grey, 20) !important; width: 100%; // on one line
}

.nav {
  &:extend(.clearfix all);
  display: block;
  li {
    display: inline-block;
    .ie7-inline-block() !important;
    margin: 0;
    padding: 0;
    &:nth-child(4n-3) {
      background-color: @red;
    }
  }
  a.disabled {
    color: @grey;
    &:hover::after {
      content: none;
    }
  }
}
```

_(This was a block of contrived less to help me test a syntax highlighter, by the way.  Don't judge me.)_
